### ISSUE TITLE
气死我啦

### ISSUE THREAD

**Issue by buddhi-deep** [Mdog2008/Kde-is-not-my-desktop#7]
kde💕💕妈妈爱你

**Comment by mdogwoop** [comment]
kde垃圾

**Comment by buddhi-deep** [comment]
kde牛逼

**Comment by chuigda** [comment]
kde is highly configurable, but totally not usable if not configured.

**Comment by buddhi-deep** [comment]
I think the time of configuring it is 100% ,worth it.

**Comment by chuigda** [comment]
> I think the time of configuring it is 100% ,worth it.

I think the time of configuring it is 100%.

**Comment by buddhi-deep** [comment]
It you have the experience of configuring it,you can finish it in 5 minutes.

**Comment by chuigda** [comment]
> It you have the experience of configuring it,you can finish it in 5 minutes.

So the time to acquire the experience is 99.9%.

**Comment by buddhi-deep** [comment]
You win......

**Comment by imkiva** [comment]
![image](https://user-images.githubusercontent.com/9902643/115951150-cbf83300-a511-11eb-85d0-10f3247324e3.png)

**Comment by buddhi-deep** [comment]
I switched to gnome and found that gnome and dconf is awesome
